version: "3.8"
services:
    esb:
        volumes:
            - ./logs:/logs
        ports:
            - "${ESB_PORT}:80"
        build: ./src/ESB
    restaurante:
        build: ./src/Restaurante
        volumes:
            - ./logs:/logs
        ports:
            - "${REST_PORT}:80"
    repartidor:
        build: ./src/Repartidor
        volumes:
            - ./logs:/logs
        ports:
            - "${REPART_PORT}:80"
    cliente:
        build: ./src/Cliente
        volumes:
            - ./logs:/logs
