version: "3.8"
services:
    esb:
        build: ./src/ESB
        ports:
            - "${ESB_PORT}:3004"
    restaurante:
        build: ./src/Restaurante
        ports:
            - "${REST_PORT}:3003"
    repartidor:
        build: ./src/Repartidor
        ports:
            - "${REPART_PORT}:3002"
    cliente:
        build: ./src/Cliente